version: '3.4'

services:
  demoapidb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=pass1234

  fullstackapi:
    container_name: full-stack-api
    image: fullstackapi
    ports:
      - 8003:80
    depends_on:
      - demoapidb
    environment:
      DatabaseServer: "demoapidb"
      DatabasePort: "1433"
      DatabaseUser: "SA"
      DatabasePassword: "pass1234"
      DatabaseName: "ResourceDB"

  angularui:
    container_name: angular-ui
    image: angularui
    ports:
      - 8005:80
